return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "bash-language-server",
      "css-lsp",
      "efm",
      "eslint_d",
      "google-java-format",
      "groovy-language-server",
      "html-lsp",
      "jdtls",
      "lemminx",
      "lua-language-server",
      "prettier",
      "pyright",
      "rust_analyzer",
      "rustfmt",
      "sonarlint-language-server",
      "stylua",
      "tailwindcss-language-server",
      "typescript-language-server",
      "xmlformatter",
      "yaml-language-server",
      "yamlfmt",
    },
  },
}
